### ISSUE TITLE
Feature request: get list of amino acids + volunteer

### ISSUE THREAD

**Issue by richelbilderbeek** [dosorio/Peptides#29]
Hi @dosorio,

For me, `Peptides` has been a very helpful package. Thanks a lot!

Sadly, I am missing something simple (and in my context useful) in your package: a way to get a character vector of all amino acids. 

I even see evidence in your code that you could also use it, for example [here](https://github.com/dosorio/Peptides/blob/master/R/aaCheck.R#L10) I see:

```
aaCheck <- function(seq){
  # ...
  check <- unlist(lapply(seq,function(sequence){
    !all(sequence%in%c("A" ,"C" ,"D" ,"E" ,"F" ,"G" ,"H" ,"I" ,"K" ,"L" ,"M" ,"N" ,"P" ,"Q" ,"R" ,"S" ,"T" ,"V" ,"W" ,"Y", "-"))
  }))
  # ...
}
```

I suggest to add a function to get all amino acids. Because it is so easy, I volunteer to write and test the function: all I need is your favorite function name for it.

Sure, it is easy to write such a function, but I feel the `Peptides` package is a natural place to put it.

Do you agree this simple function would be a worthy addition to `Peptides`?

**Comment by dosorio** [comment]
Hi @richelbilderbeek 

Sure, thank you very much for your suggestion! What do you think about `Peptides::aaSequence`? Let me know if you need any help.

Best, 

Daniel

**Comment by richelbilderbeek** [comment]
Cool! Will submit a Pull Request today :+1:

**Comment by dosorio** [comment]
Awesome, Thanks!

**Comment by richelbilderbeek** [comment]
Thank you, for being open to your users :+1:

**Comment by richelbilderbeek** [comment]
@dosorio Pull Request is in :+1:

**Comment by dosorio** [comment]
Thanks!
