### ISSUE TITLE
Feature request: Travis CI build badges on README + volunteer

### ISSUE THREAD

**Issue by richelbilderbeek** [dosorio/Peptides#31]
Hi @dosorio,

In my previous Pull Request you can observe I incorrectly thought you would not have Travis CI.

To prevent such misunderstandings from happening, I suggest to add a Travis CI build badge in the README, such as this one:

[![Build Status](https://travis-ci.org/dosorio/Peptides.svg?branch=master)](https://travis-ci.org/dosorio/Peptides)

Sure, I'd be happy to add it with a Pull Request :+1:

P.S. I do know how to fix that build error as well :zipper_mouth_face:

**Comment by dosorio** [comment]
Done in [ab64360](https://github.com/dosorio/Peptides/commit/ab64360a6965ecba32fc89c7fd05077258bffb1e). Thanks for the suggestion!
