### ISSUE TITLE
Feature request: R studio project + volunteer

### ISSUE THREAD

**Issue by richelbilderbeek** [dosorio/Peptides#32]
Hi @dosorio,

Currently, RStudio is the most used R IDE.

I suggest to add an RStudio project file to the repo.

Sure, I volunteer to do so :+1:

**Comment by dosorio** [comment]
Hi @richelbilderbeek, 

I'm an RStudio user, but I think sharing an RStudio project to manage the project is not useful for not RStudio users.

Best,

Daniel

**Comment by dosorio** [comment]
Hi @richelbilderbeek 

Thanks for your contribution. A new version of Peptides was submitted to CRAN. I renamed your function as aaList and added your name as a contributor to the package.

Best,

Daniel
