### ISSUE TITLE
mz function broken

### ISSUE THREAD

**Issue by Stortebecker** [dosorio/Peptides#42]
Hi @dosorio .
Unfortunately, your changes on the `mz` function broke it for peptides without cysteines:

```
> mz("AYNVTQAFGR")
Fehler in table(unlist(strsplit(X, "")))[["C"]] : 
  Indizierung außerhalb der Grenzen
> mz("AYNVTQAFGRC")
[1] 643.8009
```

**Comment by dosorio** [comment]
Hi @Stortebecker,

Thank you very much for letting me know. I will fix it ASAP.

Best,

Daniel

**Comment by dosorio** [comment]
Fixed in https://github.com/dosorio/Peptides/commit/2d6c80c3588bdd9cba66a5c1a41baf90dccff40d

Best,

Daniel
