### ISSUE TITLE
How to vectorise aacomp

### ISSUE THREAD

**Issue by richierocks** [dosorio/Peptides#7]
I was taking a look into the `aacomp` function, and how to vectorize it.  The big problem is that the output format doesn't scale well to examining lots of peptides.  Since the output is currently a matrix, you could extend it to have a 3 dimensional array when the input is a character vector of sequences, but these are usually rather hard to read.

My preference would be to have a data frame with a column for the input sequence, and columns for each of the composition groups, letting the user choose whether they care about counts or percentages.

Here's my suggested implementation:

``` r
aacomp2 <- function(seq, metric = c("count", "percentage")){
  metric <- match.arg(metric)
  seq <- .remove_spaces(seq)
  # Classify amino acids in a particular class and sum the absolute frequencies
  regexes <- c(
    Tiny = "[ACGST]",
    Small = "[ABCDGNPSTV]",
    Aliphatic = "[AILV]",
    Aromatic = "[FHWY]",
    NonPolar = "[ACFGILMPVWY]",
    Polar = "[DEHKNQRSTZ]",
    Charged = "[BDEHKRZ]",
    Basic = "[HKR]",
    Acidic = "[BDEZ]"
  )
  y <- lapply(
    regexes,
    stri_count_regex,
    str = seq
  )
  if(metric == "percentage")
  {
    n_chars <- nchar(seq)
    y <- lapply(y, function(yi) round(100 * yi / n_chars, 3))
  }
  data.frame(seq = seq, y)
}
```

Usage is, e.g.,:

``` r
aacomp("KWKLFKKIGIGKFLHSAKKFX")
##                     seq Tiny Small Aliphatic Aromatic NonPolar Polar Charged Basic Acidic
## 1 KWKLFKKIGIGKFLHSAKKFX    4     4         5        5       11     9       8     8      0

aacomp("KWKLFKKIGIGKFLHSAKKFX", "percentage")
##                     seq   Tiny  Small Aliphatic Aromatic NonPolar  Polar Charged  Basic Acidic
## 1 KWKLFKKIGIGKFLHSAKKFX 19.048 19.048     23.81    23.81   52.381 42.857  38.095 38.095      0
```

The only downside is that it will break code by other users relying on the structure of the return from `aacomp`.  If you think this is a problem, we may also need to provide a legacy mode that uses the existing behaviour.

**Comment by cnjr2** [comment]
+1
would be nice to have the output in data frames!

**Comment by dosorio** [comment]
Hi @richierocks! The function was vectorized and the return still is a data frame ;) It will be available in the next version in CRAN. Thanks for your suggestions!
