### ISSUE TITLE
read.xvg arbitrarily cuts off column names after 6 columns

### ISSUE THREAD

**Issue by himay81** [dosorio/Peptides#8]
Using `read.xvg()` on xvg files with any more than 6 columns of data yields `NA` for additional column names beyond the sixth. It appears the parsing loop (lines 18–20) appears to be inappropriately using the `nmax=min(P)+1` to set the upper cutoff for scraping out variable names. `nmax` sets the maximum number of criteria for `scan()` to continue looking for, not the maximal number of lines to go through. Similarly, even if it did, `min(P)+1` would only allow for 3 headers to be scanned (first was initiated by `min(P)-1`).

The `scan()` can be amended to any of the following to properly deal with any additional columns (instead of cutting off prematurely:
`scan(file,skip=min(P)-1,nmax=P1*4,what="",quiet=TRUE)[4*i]`
`scan(file,skip=min(P)-1,nlines=P1,what="",quiet=TRUE)[4*i]`
`scan(file,skip=min(P)-1,nlines=diff(range(P))+1,what="",quiet=TRUE)[4*i]` (redundant to above)

**Comment by dosorio** [comment]
Hi @himay81, the problem was solved. I change the way to determine the column number.
